<video class="hero__video-bg" playsinline autoplay muted loop poster="http://odcv-ac97.kxcdn.com/oasis-intro-video-cover.jpg">
  <source src="<?= $config->urls->templates ?>assets/video/mainstages-intro-montage.mp4" type="video/mp4">
  <!-- http://odcv-ac97.kxcdn.com/oasis-intro-short-hq.mp4 -->
  <!-- <source src="http://odcv-ac97.kxcdn.com/oasis-intro-short-hq.ogv" type="video/ogg">
  <source src="http://odcv-ac97.kxcdn.com/oasis-intro-short-hq.webm" type="video/webm"> -->
</video> 
<!-- /.large_hero__video-bg -->