

    <?php if($user->isLoggedin()) echo "<a href='$page->editURL' class='adminEditLink'>Edit</a>"; ?>

    <script src="<?= $config->urls->templates?>assets/scripts/common-bundle.js"></script>
    <script src="<?= $config->urls->templates?>assets/scripts/vendor/fa-brands.js"></script>        
    <script src="<?= $config->urls->templates?>assets/scripts/vendor/fa-solid.js"></script>    
    <script src="<?= $config->urls->templates?>assets/scripts/vendor/fontawesome.min.js"></script>
    <script src="<?= $config->urls->templates?>assets/scripts/programming-bundle.js"></script>